"""store last summary update time

Revision ID: 10866f584d19
Revises: edc5d2a45137
Create Date: 2020-06-02 10:22:00.122724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "10866f584d19"
down_revision = "edc5d2a45137"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "summary_update_time",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("last_unix_updated_ms", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("summary_update_time")
    # ### end Alembic commands ###
